// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:app/models/canvas_objects.dart';
import 'package:app/models/stroke.dart';
import 'package:app/models/workspace.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CanvasLayerAdapter());
    registerAdapter(ConnectorNodeAdapter());
    registerAdapter(DocumentNodeAdapter());
    registerAdapter(FolderAdapter());
    registerAdapter(ImageNodeAdapter());
    registerAdapter(NoteDocumentAdapter());
    registerAdapter(StrokeAdapter());
    registerAdapter(StrokePointAdapter());
    registerAdapter(TextNodeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CanvasLayerAdapter());
    registerAdapter(ConnectorNodeAdapter());
    registerAdapter(DocumentNodeAdapter());
    registerAdapter(FolderAdapter());
    registerAdapter(ImageNodeAdapter());
    registerAdapter(NoteDocumentAdapter());
    registerAdapter(StrokeAdapter());
    registerAdapter(StrokePointAdapter());
    registerAdapter(TextNodeAdapter());
  }
}
